//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using QuanLyKho.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class InputInfo : BaseViewModel
    {
        private string _Id { get; set; }
        public string Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }         
        
        private string _IdObject { get; set; }
        public string IdObject { get => _IdObject; set { _IdObject = value; OnPropertyChanged(); } }     

        private string _IdInput { get; set; }
        public string IdInput { get => _IdInput; set { _IdInput = value; OnPropertyChanged(); } }

        private Nullable<int> _Count { get; set; }
        public Nullable<int> Count { get => _Count; set { _Count = value; OnPropertyChanged(); } }

        private Nullable<double> _InputPrice { get; set; }
        public Nullable<double> InputPrice { get => _InputPrice; set { _InputPrice = value; OnPropertyChanged(); } }

        private Nullable<double> _OutputPrice { get; set; }
        public Nullable<double> OutputPrice { get => _OutputPrice; set { _OutputPrice = value; OnPropertyChanged(); } }

        private string _Status { get; set; }
        public string Status { get => _Status; set { _Status = value; OnPropertyChanged(); } }
        
        private Input _Input { get; set; }
        public virtual Input Input { get => _Input; set { _Input = value; OnPropertyChanged(); } }

        private Object _Object { get; set; }
        public virtual Object Object { get => _Object; set { _Object = value; OnPropertyChanged(); } }
    }
}
