//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using QuanLyKho.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Object : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object()
        {
            this.InputInfoes = new HashSet<InputInfo>();
            this.OutputInfoes = new HashSet<OutputInfo>();
        }
    
        private string _Id { get; set; }
        public string Id { get => _Id; set { _Id = value;OnPropertyChanged(); } }
        private string _DisplayName { get; set; }
        public string DisplayName { get => _DisplayName; set { _DisplayName = value;OnPropertyChanged(); } }
        private int _IdUnit { get; set; }
        public int IdUnit { get => _IdUnit; set { _IdUnit = value;OnPropertyChanged(); } }
        private int _IdSuplier { get; set; }
        public int IdSuplier { get => _IdSuplier; set { _IdSuplier = value;OnPropertyChanged(); } }
        private string _QRCode { get; set; }
        public string QRCode { get => _QRCode; set { _QRCode = value;OnPropertyChanged(); } }
        private string _BarCode { get; set; }
        public string BarCode { get => _BarCode; set { _BarCode = value;OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InputInfo> InputInfoes { get; set; }

        private Suplier _Suplier;
        public virtual Suplier Suplier { get => _Suplier; set { _Suplier = value;OnPropertyChanged(); } }

        private Unit _Unit;
        public virtual Unit Unit { get => _Unit; set { _Unit = value; OnPropertyChanged(); } }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputInfo> OutputInfoes { get; set; }
    }
}
