// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VD2.Models;

namespace VD2.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20190920080829_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VD2.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("CompanyName");

                    b.Property<string>("Designation");

                    b.Property<string>("Name");

                    b.Property<float>("Salary");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new { EmployeeId = 1, Address = "New York", CompanyName = "XYZ Inc", Designation = "Developer", Name = "John", Salary = 30000f },
                        new { EmployeeId = 2, Address = "New York", CompanyName = "ABC Inc", Designation = "Manager", Name = "Chris", Salary = 50000f },
                        new { EmployeeId = 3, Address = "New Delhi", CompanyName = "XYZ Inc", Designation = "Consultant", Name = "Mukesh", Salary = 20000f }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
